antlion_idle = {
    "DistractIdle2",
    "DistractIdle3",
    "DistractIdle4",
    "Idle"
}

guardian_idle = {
    "alertidle",
    "idle"
}

enemies_table = {
	["Frostlion Scout"] = {
		["Name"] = "Frostlion Scout",
		["Description"] = "Average unit of the snow insect forces. Strong in numbers.",
		["DMG"] = 11,
		["DMGT"] = "Slash",
		["DEF"] = 5,
		["DFX"] = 0,
		["DDG"] = 20,
		["MISS"] = 15,
		["AI"] = "FrostlionScoutAI()",
		["AI2"] = "UniversalDMG()",
		["LVL"] = 1,
		["EXP"] = 10,
        ["idletbl"] = antlion_idle,
        ["StunAnim"] = "AntlionStun()"
	},
	["Frostlion Skinner"] = {
		["Name"] = "Frostlion Skinner",
		["Description"] = "Its sharp talons pierce armour with a predator’s instinct. Frail.",
		["DMG"] = 7,
		["DMGT"] = "Pierce",
		["DMGP"] = 0,
		["DMGC"] = 20,
		["DEF"] = 0,
		["DFX"] = 15,
		["DDG"] = 40,
		["MISS"] = -10,
		["AI"] = "FrostlionSkinnerAI()",
		["AI2"] = "SkinnerDMG()",
		["LVL"] = 3,
		["EXP"] = 20,
        ["idletbl"] = antlion_idle,
        ["StunAnim"] = "AntlionStun()"
	},
	["Frostlion Miner"] = {
		["Name"]= "Frostlion Miner",
		["Description"] = "Its heavy and durable limbs carve tunnels in the mountain and concuss your brains.",
		["DMG"] = 25,
		["DMGT"] = "Blunt",
		["DMGS"] = 25,
		["DEF"] = 5,
		["DFX"] = 15,
		["DDG"] = -10,
		["MISS"] = 50,
		["AI"] = "FrostlionMinerAI()",
		["AI2"] = "SnowtlionMinerDMG()",
		["LVL"] = 4,
		["EXP"] = 30,
        ["idletbl"] = antlion_idle,
        ["sound_att"] = "npc/antlion/attack_double3.wav",
        ["StunAnim"] = "AntlionStun()"
	},

    -- FROSTLION GUARDIAN
    ["Frostlion Guardian"] = {
		["Name"]= "Frostlion Guardian",
		["Description"] = "This beast roams the lands with a crazed thirst for vengeance.",
		["DMG"] = 40,
		["DMGT"] = "Blunt",
		["DMGS"] = 50,
		["DEF"] = 0,
		["DFX"] = 20,
		["DDG"] = -20,
		["MISS"] = 30,
		["AI"] = "GuardianAI()",
		["AI2"] = "DefaultDMG()",
		["LVL"] = 10,
		["EXP"] = 500,
        ["idletbl"] = guardian_idle,
        ["sound_att"] = "npc/antlion/attack_double3.wav",
        ["StunAnim"] = "GuardianStun()",
        ["PainAnim"] = "GuardianPain()"
	},
    ["Frostlion Prince"] = {
		["Name"] = "Frostlion Prince",
		["Description"] = "Swift and of sharp senses, the Prince seeks out dazed targets and executes them.",
		["DMG"] = 10,
		["DMGT"] = "Pierce",
		["DMGP"] = 0,
		["DMGC"] = 35,
		["DEF"] = 0,
		["DFX"] = -10,
		["DDG"] = 25,
		["MISS"] = -30,
		["AI"] = "PrinceAI()",
		["AI2"] = "SkinnerDMG()",
		["LVL"] = 6,
		["EXP"] = 100,
        ["idletbl"] = antlion_idle,
        ["StunAnim"] = "AntlionStun()"
	}
}

items_table = {
    ["OldCrowbar"] = {
        ["Name"] = "Old Crowbar",
        ["Desc"] = "Standard-issue. Dull, but has withstood the test of time.",
        ["Desc2"] = "No bonus effects.",
        ["Desc3"] = "+25% MGT, +25% DFE, +25% CEL",
        ["dmgtype"] = "Slash",
        ["BaseAcc"] = 75,
        ["DMG1"] = 13,
        ["DMG2"] = 17,
        ["SCS1"] = 15,
        ["SCS2"] = 15,
        ["SCS3"] = 15,
        ["Icon"] = "items/entourage_oldcrowbar.png",
        ["Type"] = "Weapon",
        ["PDEF"] = "0",
        ["PSDL"] = 0,
        ["PAGI"] = 0,
        ["func"] = "OldCrowbar()",
        ["targets"] = 1
    },
    ["RustyKnife"] = {
        ["Name"] = "Rusty Knife",
        ["Desc"] = "Only good for thrusting; half-digested.",
        ["Desc2"] = "+2 Celerity",
        ["Desc3"] = "+75% CLE, +25% FCS, 25% armour penetration",
        ["dmgtype"] = "Pierce",
        ["BaseAcc"] = 95,
        ["DMG3"] = 4,
        ["Icon"] = "items/entourage_rustyknife.png",
        ["Type"] = "Weapon",
        ["PDEF"] = "0",
       ["PSDL"] = 0,
        ["PAGI"] = 2,
        ["func"] = "RustyKnife()",
        ["targets"] = 1
    },
    ["WoodenClub"] = {
        ["Name"] = "Wooden Club",
        ["Desc"] = "Desperate attempt at a bash weapon. Heavy, unwieldy.",
        ["Desc2"] = "No bonus effects.",
        ["Desc3"] = "+15% MGT, +10% damage per 1 CST",
        ["dmgtype"] = "Blunt",
        ["BaseAcc"] = 40,
        ["DMG4"] = 22,
        ["DMG5"] = 28,
        ["Icon"] = "items/entourage_woodenclub.png",
        ["Type"] = "Weapon",
        ["PDEF"] = "0",
        ["PSDL"] = 0,
        ["PAGI"] = 0,
        ["func"] = "WoodenClub()",
        ["targets"] = 1
    },
    ["EmptySlot"] = {
        ["Name"] = "Fists",
        ["Type"] = "Weapon",
        ["Icon"] = "items/entourage_emptyslot.png",
        ["DMG4"] = 1,
       ["DMG5"] = 3,
        ["dmgtype"] = "Blunt",
        ["BaseAcc"] = 95,
        ["Desc"] = "Conquer the world as nature intended.",
        ["Desc2"] = "-5 Defence, +2 Celerity",
        ["Desc3"] = "+100% DFE, +25% damage per 1 MGT",
        ["PDEF"] = "-5",
        ["PSDL"] = 0,
        ["PAGI"] = 2,
        ["func"] = "Fists()",
        ["targets"] = 1
    },
    ["RopeSpear"] = {
        ["Name"] = "Rope Spear",
        ["Type"] = "Weapon",
        ["Icon"] = "items/entourage_ropespear.png",
        ["DMG1"] = 10,
        ["DMG2"] = 14,
        ["DMG3"] = 7,
        ["DMG4"] = 4,
       ["DMG5"] = 20,
        ["dmgtype"] = "Multiple",
        ["BaseAcc"] = 95,
        ["Desc"] = "Knife on a long stick, reinforced with rope. Multi-purpose.",
       ["Desc2"] = "-1 Celerity, +1 Defence",
        ["Desc3"] = "+75% MGT / 75% CLE, 50% armour pen. / No scaling",
        ["PDEF"] = 0,
        ["PSDL"] = 0,
        ["PAGI"] = -1,
        ["func"] = "RopeSpear()",
        ["targets"] = 1
    },
    ["SalvagedBlade"] = {
        ["Name"] = "Salvaged Blade",
        ["Type"] = "Weapon",
        ["Icon"] = "items/entourage_salvagedblade.png",
        ["DMG1"] = 15,
        ["DMG2"] = 18,
        ["dmgtype"] = "Slash",
        ["BaseAcc"] = 65,
        ["Desc"] = "Crude metal marks this weapon's sharp edge.",
       ["Desc2"] = "None",
        ["Desc3"] = "+100% MGT, +75% FCS",
        ["PDEF"] = 0,
        ["PSDL"] = 0,
        ["PAGI"] = 0,
        ["func"] = "SalvagedBlade()",
        ["targets"] = 1
    },
    ["ClothArmour"] = {
        ["Name"] = "Cloth Armour",
        ["Type"] = "Armour",
        ["Icon"] = "items/entourage_clotharmour.png",
        ["Desc"] = "Standard-issue clothes for scouts.",
       ["Desc2"] = "+5 Dodge",
        ["PDEF"] = 5,
        ["PDFX"] = 0,
        ["PDG"] = 5,
        ["PAGI"] = 0
    },
    ["SlimArmour"] = {
        ["Name"] = "Slim Armour",
        ["Type"] = "Armour",
        ["Icon"] = "items/entourage_slimarmour.png",
        ["Desc"] = "Slim clothes with a premise on light weight.",
       ["Desc2"] = "+12 Dodge, +3 Celerity",
        ["PDEF"] = 2,
        ["PDFX"] = 0,
        ["PDG"] = 12,
        ["PAGI"] = 3
    },
    ["PaddedArmour"] = {
        ["Name"] = "Padded Armour",
        ["Type"] = "Armour",
        ["Icon"] = "items/entourage_paddedarmour.png",
        ["Desc"] = "Reinforced standard armour. Heavier, sturdier.",
       ["Desc2"] = "No bonus effects.",
        ["PDEF"] = 15,
        ["PDFX"] = 0,
        ["PDG"] = 0,
        ["PAGI"] = 0
    },
    ["PrecisionArmour"] = {
        ["Name"] = "Precision Armour",
        ["Type"] = "Armour",
        ["Icon"] = "items/entourage_precisionarmour.png",
        ["Desc"] = "Unique set of protection that covers only vital body parts.",
       ["Desc2"] = "+8 Dodge, +1 CLE",
        ["PDEF"] = 3,
        ["PDFX"] = 14,
        ["PDG"] = 8,
        ["PAGI"] = 1
    },
    ["ImpracticalArmour"] = {
        ["Name"] = "Impractical Armour",
        ["Type"] = "Armour",
        ["Icon"] = "items/entourage_impracticalarmour.png",
        ["Desc"] = "A shoddy attempt at plate armour.",
       ["Desc2"] = "-50 Dodge, -3 Celerity",
        ["PDEF"] = 0,
        ["PDFX"] = 60,
        ["PDG"] = -50,
        ["PAGI"] = -5
    },
    ["EmptySlot2"] = {
        ["Name"] = "None",
        ["Type"] = "Empty",
        ["Icon"] = "items/entourage_emptyslot.png",
        ["Desc"] = "Light as a feather - as feeble as one.",
       ["Desc2"] = "+30 Dodge, +3 Celerity.",
        ["PDEF"] = -35,
        ["PDFX"] = 0,
        ["PDG"] = 30,
        ["PAGI"] = 3
    },
    ["KillerSword"] = {
        ["Name"] = "Lynxsie's Greatsword",
        ["Desc"] = "Used by the legendary Lynxsie to conquer Calradia.",
       ["Desc2"] = "Where'd my rapier go?",
        ["Desc3"] = "No scaling",
        ["dmgtype"] = "Slash",
        ["BaseAcc"] = 200,
        ["DMG1"] = 100,
        ["DMG2"] = 100,
        ["Icon"] = "items/entourage_killersword.png",
        ["Type"] = "Weapon",
        ["PDEF"] = 0,
        ["PSDL"] = 0,
        ["PAGI"] = 0,
        ["func"] = "KillerSword()",
        ["targets"] = 1
    }
}